### ISSUE TITLE
Another exception was thrown: A RenderFlex overflowed by 150 pixels on the right.

### ISSUE THREAD

**Issue by nEdAy** [Meruya-Techhnology/network_inspector#31]
<img src="https://user-images.githubusercontent.com/10076735/165432166-6b2bb876-48cd-46ac-98ef-0cf2e09b3290.jpg" height="400">

======== Exception caught by rendering library =====================================================
The following assertion was thrown during layout:
A RenderFlex overflowed by 174 pixels on the right.

The relevant error-causing widget was: 
  ActivityPage ActivityPage:file:///Users/neday/StudioProjects/sunac-projects/app-zx/sunac_flutter/lib/widgets/developer_widget.dart:55:37
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

**Comment by dwievermos** [comment]
Hey @nEdAy , i really thank you personally to looking after this package. I will grant you as a contributor for your contribution +3 issues to this repository, i really appreciate it thank you very much. Btw i just realize there is an issues for this, indeed we need to add Expanded also the widget test so the layout issues won't appear in the future. Thanks again !

**Comment by dwikurniantom** [comment]
Hey @nEdAy , i really thank you personally to looking after this package. I will grant you as a contributor for your contribution +3 issues to this repository, i really appreciate it thank you very much. Btw i just realize there is an issues for this, indeed we need to add Expanded also the widget test so the layout issues won't appear in the future. Thanks again !
