### ISSUE TITLE
No mix use of theme color and hard coded color please

### ISSUE THREAD

**Issue by timnew** [Meruya-Techhnology/network_inspector#49]
**Describe the bug**

The details screen is not readable when app has a dark theme.
Please don't mix use the of the theme color and hard coded color.

**To Reproduce**
1. Set the theme to a dark one
2. Open activity details screen.

**Expected behavior**

The screen is dark themed, but got a white screen with white text.

**Screenshots**
![CleanShot 2023-01-19 at 11 01 55@2x](https://user-images.githubusercontent.com/1287238/213324456-5be3a5fa-5f72-4ebe-850d-1dfefdc11ca5.png)

**Smartphone (please complete the following information):**
 - network_inspector: ^1.0.3

**Comment by dwikurniantom** [comment]
Sorry for late response, ah see. Thank you for your concern, i will fix this. I think the text need to adjust to use the parent theme instead using it own style. thanks again !

**Comment by dwikurniantom** [comment]
This issue will be included in the next release `1.0.4` to support material 3 and dark mode
